### ISSUE TITLE
Get HTTP 500 error on add GOV-ID

### ISSUE THREAD

**Issue by fanningert** [ric2016/gov4webtrees#1]
I get following PHP-Error for the HTTP-500 error (Internal Server Error) when I would like to add a GOV-ID.

```
PHP message: PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /var/www/example.com/modules_v3/gov4webtrees/FunctionsGov.php:581
Stack trace:
#0 /var/www/example.com/modules_v3/gov4webtrees/FunctionsGov.php(785): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::loadGovObject('object_215349', '1518358763978')
#1 /var/www/example.com/modules_v3/gov4webtrees/AjaxRequests.php(18): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::retrieveGovObjectSnapshot('2420256', 'object_215349', '1518358763978', 'de')
#2 /var/www/example.com/modules_v3/gov4webtrees/ajaxExpand.php(43): Cissee\Webtrees\Module\Gov4Webtrees\AjaxRequests::expand()
#3 {main} thrown in /var/www/example.com/modules_v3/gov4webtrees/FunctionsGov.php on line 581
```
Here the url to this.
`https://example.com/modules_v3/gov4webtrees/ajaxExpand.php?placeId=Graz,%20Steiermark,%20Austria&type=MAIN&id=object_215349&version=1518358763978&julianDay=2420256&locale=de&allowSettlements=true`

Active are following plugins from your site (Installed you package).
* Hooks
* Facts and Events
* Gov4Webtrees

I'am using webtress 1.7.9.

**Comment by ric2016** [comment]
The first thing to check is whether the php Soap Client is enabled, see e.g. [here](https://stackoverflow.com/questions/11391442/fatal-error-class-soapclient-not-found).

You can check this via Control Panel > Website > Server information. Search for "Soap Client", it should be set to "enabled". If that's not the case, you'll have to adjust your php.ini settings.

**Comment by fanningert** [comment]
Thank you for the help. It is working now. The problem was the missing php-soap client.

**Comment by ric2016** [comment]
Great - I'll add a note to the module (I wasn't aware of this potential problem, apparently this library is enabled most of the time).
