### ISSUE TITLE
Module not installable!?

### ISSUE THREAD

**Issue by marku5** [ric2016/gov4webtrees#10]
Hello Richard,
I just updated wt to 1.7.13 and then started to update your great modules gov4webtrees and extended_relationships.

After copying and activating vesta and hooks I started copying the dir gov4webtrees.
To check whether the modules are installed prperly nad have the right version number I tried to open the WT-page webtrees/admin_modules.php...
...but it was just blank.
When deleting the file module.php from the module dir the WT-module-page loads, but of course xour module is not listed.

Any idea?
Tnx, Markus

**Comment by ric2016** [comment]
I haven't tested the modules with the latest 1.7 versions, I'll check this.

**Comment by ric2016** [comment]
I cannot reproduce this with 1.7.13 - What's your php version? Is there anything in the error logs?

**Comment by marku5** [comment]
PHP-Version is 7.2.13 and nothing in the logs. Hmmm....

**Comment by ric2016** [comment]
Other things to try:
Is there anything in the browser's developer tools maybe? Like a failed request on the 'Network' tab? Did you also check the server's php error log?

Maybe some file wasn't copied properly - Try using a 'fresh' gov4webtrees folder directly from the release zip.

**Comment by marku5** [comment]
I deleted module folders and copied folders from latest release (https://cissee.de/vesta.latest.zip):
"modules_v3\vesta_common_lib", "modules_v3\hooks_repackaged" + as test "modules_v3\gov4webtrees"
=> Still I get the white page when calling webtrees/admin_modules.php

**Comment by ric2016** [comment]
There has to be an error message somewhere.
(https://wiki.webtrees.net/en/Frequently_Asked_Questions#Installation)
You'll have to find this error message, or configure php to show errors 'on the screen'.
There is no other way for us to make progress here I'm afraid.
Sorry about this - This never occured with earlier releases?

**Comment by marku5** [comment]
Hi Richard,
thanks for your patience: Everything now works as expected!
Silly me: I forgot to copy the "xxx_with_hooks" files...

**Comment by ric2016** [comment]
Good to know that it works now.
I'll check if there is a better way to handle cases like this (it would be better if missing dependent modules wouldn't affect webtrees itself, just the 'broken' modules) in the 2.x version of the modules.
