### ISSUE TITLE
is not working on webtrees 2.0 final

### ISSUE THREAD

**Issue by HonkXL** [ric2016/gov4webtrees#11]
This extension seems not to work in webtrees 2.0. Start page of webtrees brings up an error message when activating this extension.
Message is similar to the on the theme compact_theme_adjuster 
At moment I can not reproduce the error because I need my webtrees online at moment. But if required I can send the message here.

**Comment by ric2016** [comment]
There are several small adjustments required, which I have already prepared.

Unfortunately, there is also a bug (https://github.com/fisharebest/webtrees/issues/2830) which will have to be fixed in webtrees itself.

**Comment by ric2016** [comment]
Note also that this is the 1.x branch.
The 2.x branch is at https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees.

**Comment by ric2016** [comment]
I have now released a version compatible with the current webtrees release.
(with a workaround for the webtrees bug, so this should work with webtrees 2.0.0 as well as the current dev version)
