### ISSUE TITLE
Error 500 on current webtrees 1.7.17

### ISSUE THREAD

**Issue by bmarwell** [ric2016/gov4webtrees#12]
Hi,

on the current webtrees release every page will output a 500 error.

Can you look into this?

**Comment by ric2016** [comment]
The latest 1.x webtrees release is 1.7.16 (I don't support unreleased 1.7.x dev versions).
It works for me in combination with the latest 1.x gov4webtrees release, which is 1.7.10.1.

Are you using these versions (and the latest versions of all dependent Vesta custom modules)? 
Which php version?
What is the error message?

**Comment by bmarwell** [comment]
Using .16, just had thick fingers. Sorry.

Didn't have time to check any logs. Just 500 of you open any page.

I also deleted the old tables from the gov fact plugin

**Comment by ric2016** [comment]
How am I supposed to fix this if you don't give me anything to work with?
As I have said, I cannot reproduce it.

> I also deleted the old tables from the gov fact plugin

That's probably not a good idea, why would you do that?
What is the "gov fact plugin"?

**Comment by ric2016** [comment]
Closed: Not enough information provided to reproduce.

**Comment by bmarwell** [comment]
Sorry, was busy. I'll try to get the logs soon
