### ISSUE TITLE
Unexpected language in GOV hierarchy (2.x)

### ISSUE THREAD

**Issue by ric2016** [ric2016/gov4webtrees#15]
![Screenshot (20)_LI](https://user-images.githubusercontent.com/6324175/88194753-77045500-cc3f-11ea-8a1b-aecf91c54638.jpg)

Why is the used language slo instead of deu for Österreich?

_Originally posted by @hartenthaler in https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/issues/19#issuecomment-662519756_

**Comment by ric2016** [comment]
The Entry for Austria in the GOV, prior to your recent changes, looked like this ([link](http://gov.genealogy.net/recentChanges/showOldQuicktext/object_215340?version=46)):

```
object_215340
	gehört ab 1995 zu object_1176980,
	hat externe Kennung  wikidata:Q40,
	heißt  (auf slo) Rakúsko,
	heißt 2017  (auf dan) Østrig,
	heißt 2017  (auf deu) Republik Österreich,
	heißt 2017  (auf deu) Österreich,
	heißt 2017  (auf eng) Austria,
	heißt 2017  (auf fre) Autriche,
	heißt 2017  (auf swe) Österrike,
	ist ab 1918 bis 1938 (auf deu) Republik,
	ist ab 1945 (auf deu) Bundesstaat;
``` 

So "Rakúsko" was the only available label for any date other than 2017. This problematic modelling in GOV occurs (or occured) for several countries, I (and others) have asked about this via the mailing list and via mail directly, without any reply.

The current entry for Austria, after your changes, is ok.

The GOV data is cached by the Gov4Webtrees module though. You should get a proper label when resetting the hierarchy for this place (by simply entering the same GOV id again).

**Comment by hartenthaler** [comment]
I have seen and modified the problematic modeling in GOV. The GOV data is still cached and it still shows Rakúsko. I tried to refresh the cache for my shared place AUT without success:
- deleted the GOV id; entered the GOV id again
- entered another (wrong) GOV id, which was shown correctly; entered the correct GOV id again (again Rakúsko)

**Comment by ric2016** [comment]
ok, either the reset functionality is incomplete then - or it is a different issue. I assume the former because I cannot reproduce this.

I'll look into it - In the meantime, you can try to reset all cached GOV data via the module configuration (Id mappings are kept).

**Comment by hartenthaler** [comment]
global "reset cache" was successful!

**Comment by ric2016** [comment]
Turns out the reset functionality has only been implemented for direct GOV Id mappings (outside GEDCOM). I'll fix this.

**Comment by ric2016** [comment]
The latest release has an extra button for _GOV under _LOC which allows to reload the hierarchy from the GOV-Server.
