### ISSUE TITLE
No GOV ID set for... not translated to German

### ISSUE THREAD

**Issue by HonkXL** [ric2016/gov4webtrees#8]
Missing the text for the German translation of "No GOV id set for..."
I would recommend to translate it like:

Keine GOV-ID für % gesetzt. (where % is the name of the city).

And an other recommendation: the button shows the text "Id setzen".
I think it is more common to write ID instead of Id.

<img width="558" alt="govtranslation" src="https://user-images.githubusercontent.com/16715040/52539976-a2b1b900-2d84-11e9-81c4-00bad6916917.png">

**Comment by ric2016** [comment]
Will be fixed in next release as suggested.
(attached [de.zip](https://github.com/ric2016/gov4webtrees/files/2849529/de.zip) contains these changes)

**Comment by HonkXL** [comment]
Looks much better now - thank you! :-)

**Comment by marku5** [comment]
Another Idea: Add a link to http://gov.genealogy.net to words "GOV" or "GOV-ID", especially if the ID is missing.
